### ISSUE TITLE
Sending emails with attachements does not work well when using this library

### ISSUE THREAD

**Issue by poojasgada** [elbuo8/sendgrid-django#15]
Hi, 

I used to send HTML emails with SMTP via sendgrid. But unfortunately, had to switch back to webapi due to some client issue. When i use sendgrid-django, to send these emails, the attachments end up being malformed.

Here's a snippet of my django code which is sending out HTML emails with attachements:

```
# To attach the image inline.
  msg = EmailMultiAlternatives(subject, text_content, from_email, to_email)
  msg.attach_alternative(html_content, "text/html")
  msg.mixed_subtype = 'related'

  fp = open(IMAGE_PATH+ imgName, 'rb')
  msg_img = MIMEImage(fp.read(), name=imgName)
  fp.close()
  msg_img.add_header('Content-ID', '<{0}>'.format(imgName))
  msg.attach(msg_img)
```

And then i use send_messages() to send out these messages. 

In the email that gets sent out, the attachments seem to be malformed. Am i missing something ?

Appreciate your help.

**Comment by davidfischer-ch** [comment]
@poojasgada Its worth nothing but can you give a try to my fork?
https://github.com/CloudNcodeInc/sendgrid-django
I am using it and it works well.

**Comment by poojasgada** [comment]
Hi @davidfischer-ch . I ended up modifying the library itself. It was not decoding the base64 encoded image and was not adding a content-id header. After doing these two changes, it works as expected.

**Comment by mallyvai** [comment]
@poojasgada Do you have a patch for this you can upload?

**Comment by andriisoldatenko** [comment]
For Python3 working example:
```
from django.core.mail import EmailMultiAlternatives

mail = EmailMultiAlternatives(
        subject=subject,
        body=body,
        from_email=from_email,
        to=[to_email]
    )
file = open('somefilename.pdf', 'rb').read()
mail.attachments = [('full_report.pdf', file, 'application/pdf')]
mail.send()
```
For more details:
https://github.com/elbuo8/sendgrid-django/blob/master/sgbackend/mail.py#L96-L111

**Comment by elbuo8** [comment]
@poojasgada still seeing this issue?
