### ISSUE TITLE
add fallback backend?

### ISSUE THREAD

**Issue by evgenyfadeev** [elbuo8/sendgrid-django#16]
Would it make sense to add a SENDGRID_FALLBACK_EMAIL_BACKEND setting
so that if SendGrid fails to dispatch a message, a "spare" backend would be used?

For instance, when the daily quota runs out, some other backend would still send messages for the site.

I'll be happy to make a PR if this might be a good feature.

**Comment by davidfischer-ch** [comment]
It's an awesome idea to chain free plans of email delivery platforms :-)

**Comment by elbuo8** [comment]
This seems more of something you would do in your end instead of in the library IMO.
