### ISSUE TITLE
Upgrade to SendGrid v3 Web API

### ISSUE THREAD

**Issue by thinkingserious** [elbuo8/sendgrid-django#22]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

**Comment by roelio** [comment]
We have upgraded the extension for use with v3 at https://github.com/stamkracht/sendgrid-django
Be aware that the extra headers are not working in this version.
It still needs some work, but we have to start somewhere ;-)

**Comment by thinkingserious** [comment]
Thanks @roelio, that's awesome!

**Comment by mbernier** [comment]
Hey @elbuo8 would you be up for merging @roelio's code into your repo? :)

**Comment by elbuo8** [comment]
@mbernier sure 👍 

@roelio mind sending a PR?

**Comment by andriisoldatenko** [comment]
https://github.com/elbuo8/sendgrid-django/pull/26

**Comment by RobertBroersma** [comment]
Any news on this?

**Comment by andriisoldatenko** [comment]
@RobertBroersma Done in https://github.com/elbuo8/sendgrid-django/pull/26
I think we can close issue.
cc @thinkingserious

**Comment by thinkingserious** [comment]
Awesome!
