### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [elbuo8/sendgrid-django#24]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [sendgrid-django](https://pypi.python.org/pypi/sendgrid-django), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install sendgrid-django with just the wheel, without having to do any extra work.

**Comment by elbuo8** [comment]
@andriisoldatenko you up for this? Otherwise I'll have a stab at it.

**Comment by andriisoldatenko** [comment]
@elbuo8 
nope, I'm not working on it now.

**Comment by kavdev** [comment]
@elbuo8: Wheel support is pretty quick. See #42.

**Comment by kavdev** [comment]
(this can be closed with the merge)
