### ISSUE TITLE
conflict with sendgrid python v3.6.0

### ISSUE THREAD

**Issue by letlet** [elbuo8/sendgrid-django#28]
When I upgraded sendgrid python to version 3.6.0
my django project use sendgrid-django as email backend show such error:
`'module' object has no attribute 'SendGridClient'`
Then I uninstalled  sendgrid  python v3.6.0 and installed  sendgrid  python v1.4.0, sendgrid-django work again.

**Comment by andriisoldatenko** [comment]
@letlet Can you please add more info. Python version, Django version etc.

**Comment by letlet** [comment]
python2.7 django1.8.5
