### ISSUE TITLE
User Agent Tracking 

### ISSUE THREAD

**Issue by elbuo8** [elbuo8/sendgrid-django#35]
@thinkingserious would it make sense for you if we overrode the `user-agent` header with one that indicates traffic for this library? Would be nice to get some usage statistics. We would use the same format of course.

Thoughts @andriisoldatenko ?

**Comment by andriisoldatenko** [comment]
Sound interesting.

**Comment by thinkingserious** [comment]
@elbuo8 that sounds good to me. Thanks!

**Comment by elbuo8** [comment]
https://github.com/elbuo8/sendgrid-django/pull/37

@thinkingserious

**Comment by andriisoldatenko** [comment]
merged PR #37
