### ISSUE TITLE
Incompatible with Python 3.5.2?

### ISSUE THREAD

**Issue by Kangaroux** [elbuo8/sendgrid-django#38]
Just upgraded to 3.5.2 from 3.4.3 and I'm getting the following error when trying to send an email with an api key:

```
File "/usr/lib/python3.5/http/client.py", line 1083, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))    
ValueError: Invalid header value b'Bearer <APIKEY>\r'
```

**Comment by andriisoldatenko** [comment]
Hi @Kangaroux 
I using Python 3.5.2 on production.
```
(example.com) vagrant@vagrant-ubuntu-trusty-64:~$ python -V
Python 3.5.2
(example.com) vagrant@vagrant-ubuntu-trusty-64:~$ pip freeze | grep sendgrid
sendgrid==3.6.3
sendgrid-django==4.0.1
```
Everything works for me.
Can you please show me your how you put in settings `APIKEY` encoding?

**Comment by Kangaroux** [comment]
settings.py

    EMAIL_BACKEND = "sgbackend.SendGridBackend"
    SENDGRID_API_KEY = os.environ.get("SENDGRID_API")

deploy.sh

    export SENDGRID_API="SG.abcdefg1234"

**Comment by andriisoldatenko** [comment]
@Kangaroux try to
```
SENDGRID_API_KEY = str.encode(os.environ.get("SENDGRID_API"))
```

**Comment by andriisoldatenko** [comment]
more info at http://stackoverflow.com/questions/7585435/best-way-to-convert-string-to-bytes-in-python-3

**Comment by andriisoldatenko** [comment]
btw I tried using your approach all is working for me.
