### ISSUE TITLE
From name is always empty

### ISSUE THREAD

**Issue by GlennV** [elbuo8/sendgrid-django#39]
In previous versions, you could just do `from_email="Company <info@company.com>"`.

However, as of https://github.com/elbuo8/sendgrid-django/commit/9cb266812d6beaf063fa26359f12ebc3f71f4b8d, only the e-mail is passed to the new Email() method of the sendgrid package.

This means the From name is now always empty.

**Comment by andriisoldatenko** [comment]
Hi @GlennV 
I don't understand your comment, can you please review new example https://github.com/elbuo8/sendgrid-django#example?
Or add your full example:
```
send_mail("Your Subject", "This is a simple text email body.",
  "Yamil Asusta <hello@yamilasusta.com>", ["yamil@sendgrid.com"])
```

Just tested:
```
In [3]: send_mail("Your Subject", "This is a simple text email body.", "Andrii Soldatenko <hello@asoldatenko.com>", ["andrii.soldatenko@gmail.com"])
Out[3]: 1
```
![image](https://cloud.githubusercontent.com/assets/1374633/20647168/e2159a04-b495-11e6-95f9-20c2bb5fc21f.png)

**Comment by GlennV** [comment]
The problem is clear from your screenshot, your name "Andrii Soldatenko" is not shown as sender. Only your e-mail is shown. With sendgrid==1.4.0 and sendgrid-django==1.4.0, the name is also added to the From: header.

**Comment by andriisoldatenko** [comment]
thanks, will check.

**Comment by andriisoldatenko** [comment]
@GlennV Thanks for report issue. I'm working on fix.
