### ISSUE TITLE
Error sending attachments with mimetype text/*

### ISSUE THREAD

**Issue by glujan** [elbuo8/sendgrid-django#61]
When sending a text attachment, Django will automatically try to convert from bytes to string ([here](https://github.com/django/django/blob/546412e6731e5e31b8450c35e3dae8ec26bc008c/django/core/mail/message.py#L321-L328), it's described in a docstring).

Unfortunately `sendgrid-django` is expecting bytes objects only ([here](https://github.com/elbuo8/sendgrid-django/blob/476bfbec0cd85cab32b4240bc1768902bfc543d2/sgbackend/mail.py#L114))

To reproduce this you will need:
 * Python 3 (I'm using Python 3.6)
 * Add attachments using tuple with mimetype set to `text/*` where `*` is any string

Minimal code example (assuming `sendgrid-django` is configured):
```
from django.core.mail import EmailMessage

attachments = (
    ('file.txt', b'File content', 'text/plain'),
)
email = EmailMessage(
    subject='Email subject',
    body='Email body',
    from_email='from@example.com',
    to=('to@example.com', ),
    attachments=attachments,
)
email.send(fail_silently=False)  # <--- raises TypeError: a bytes-like object is required, not 'str'
```

**Comment by andriisoldatenko** [comment]
@glujan thanks for reporting I'll take a look.

**Comment by jayhale** [comment]
Verified the issue: https://github.com/jayhale/sendgrid-django-61/tree/88dcf909d0067f85fc2bf8d9e5244464a434f045

Will propose a solution shortly.

**Comment by andriisoldatenko** [comment]
Thanks for detailed report. I'll try to fix.

**Comment by Ankit-Kr-Singh** [comment]
This is how I got it working:

Goto sgbackend/mail.py

remove line 147 and add the below code:

`try:
          attachment_object = attachment[1].encode()
  except Exception as ex:
          attachment_object = attachment[1]
base64_attachment = base64.b64encode(attachment_object)`

This might not be the best solution but it works fine.

**Comment by RandomJo** [comment]
I am having this problem as well with Python 3.6 and can verify that the fix from Ankit-KrSingh fixes the issue for me.

**Comment by glujan** [comment]
Can I do anything to help closing that issue? I think I may propose my patch based on @jayhale work or create a new one.

**Comment by glujan** [comment]
This library looks like no longer maintained. Thanks for providing it in the first place, closing this old issue.
