### ISSUE TITLE
The sample code in the readme uses a reserved header.

### ISSUE THREAD

**Issue by BillBrower** [elbuo8/sendgrid-django#65]
Using the sample code you'll get a 400 back from Sendgrid because `Reply-To` is a [reserved header](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.headers).

**Comment by jayhale** [comment]
@BillBrower could you create a sample to reproduce the error? Please include the full error message as well.

**Comment by jayhale** [comment]
This is fixed by #58. Recommend closing.

Evidence: https://github.com/jayhale/sendgrid-django-64

**Comment by BillBrower** [comment]
Thanks for fixing this!
