### ISSUE TITLE
HTTPError not being caught

### ISSUE THREAD

**Issue by danniehakan** [elbuo8/sendgrid-django#74]
I'm having issues with an `HTTPError` not being caught by `SendgridBackend.send_messages`. The error is `python_http_client.exceptions.BadRequestsError: HTTP Error 400: Bad Request`, from what I can see it should be caught if `fail_silently = True`(rather, it should not be rethrown), which is the case in my unittest.

Python: 3.6.0
Django: 1.10.7

Any ideas?

**Comment by danniehakan** [comment]
Could it be an issue related to python 3 compatibility?

**Comment by danniehakan** [comment]
It seems like the exceptions that are raised, contained in `python_http_client.exceptions`, are actually not the ones we are trying to catch, since they are not based on `urllib`.

**Comment by wwrinkle** [comment]
I'm having the same issue. Any help would be appreciated.
