### ISSUE TITLE
release new version!

### ISSUE THREAD

**Issue by jschneier** [elbuo8/sendgrid-django#8]
Hey, just want to be able to use my patch off pypi! Thanks so much!

**Comment by grahamc** [comment]
Yes, please `python setup.py sdist upload` to deploy the execfile bugfix as well.

- Graham

**Comment by elbuo8** [comment]
:boom:

**Comment by grahamc** [comment]
Score! Thank you! :)



- Graham

**Comment by grahamc** [comment]
:catwithhearteyes:



- Graham
